"""
Terragrunt Forge — MCP Server for generating Terragrunt stacks.

A Model Context Protocol (MCP) server that Claude can call as a tool
to generate production-ready Terragrunt configurations for AWS.

Based on patterns from the stack-forge project.

Usage:
    pip install "mcp[cli]" pydantic jinja2 pyyaml
    python mcp_server.py
"""

from __future__ import annotations

import json
import logging
import textwrap
from enum import StrEnum
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, Field

# ─── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("terragrunt-forge")

# ─── MCP Server ─────────────────────────────────────────────────────────────────
mcp = FastMCP(
    "terragrunt-forge",
    instructions="Generate production-ready Terragrunt stacks for AWS infrastructure",
)

SKILL_PATH = Path(__file__).parent / "TERRAGRUNT_SKILL.md"

# ═══════════════════════════════════════════════════════════════════════════════
#  Models
# ═══════════════════════════════════════════════════════════════════════════════

class Environment(StrEnum):
    DEV = "dev"
    STAGING = "staging"
    PROD = "prod"


class ResourceType(StrEnum):
    VPC = "vpc"
    S3_BUCKET = "s3_bucket"
    EKS = "eks"
    RDS = "rds"
    DYNAMODB = "dynamodb"
    LAMBDA = "lambda"
    IAM_ROLE = "iam_role"
    SECURITY_GROUP = "security_group"
    SECRETS_MANAGER = "secrets_manager"
    ECR = "ecr"


class ResourceConfig(BaseModel):
    name: str
    type: ResourceType
    variables: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)


class StackConfig(BaseModel):
    name: str
    category: str = "general"  # network, compute, data, security, general
    environment: Environment = Environment.DEV
    region: str = "us-west-2"
    resources: list[ResourceConfig] = Field(default_factory=list)


class ProjectConfig(BaseModel):
    name: str
    organization: str
    environments: list[Environment] = Field(
        default_factory=lambda: [Environment.DEV, Environment.STAGING, Environment.PROD]
    )
    default_region: str = "us-west-2"
    stacks: list[StackConfig] = Field(default_factory=list)
    output_dir: str = "infrastructure"


# ═══════════════════════════════════════════════════════════════════════════════
#  Template Generators
# ═══════════════════════════════════════════════════════════════════════════════

# ---------- Terraform module templates (main.tf) ----------

TERRAFORM_TEMPLATES: dict[str, str] = {}

TERRAFORM_TEMPLATES["vpc"] = textwrap.dedent("""\
    # VPC Module — Generated by Terragrunt Forge

    locals {
      name = "${var.name}-${var.environment}"
      azs  = slice(data.aws_availability_zones.available.names, 0, var.az_count)
    }

    data "aws_availability_zones" "available" { state = "available" }

    resource "aws_vpc" "this" {
      cidr_block           = var.vpc_cidr
      enable_dns_hostnames = true
      enable_dns_support   = true
      tags = merge(var.tags, { Name = local.name })
    }

    resource "aws_internet_gateway" "this" {
      vpc_id = aws_vpc.this.id
      tags   = merge(var.tags, { Name = "${local.name}-igw" })
    }

    resource "aws_subnet" "public" {
      count                   = var.az_count
      vpc_id                  = aws_vpc.this.id
      cidr_block              = cidrsubnet(var.vpc_cidr, 4, count.index)
      availability_zone       = local.azs[count.index]
      map_public_ip_on_launch = true
      tags = merge(var.tags, {
        Name                     = "${local.name}-public-${local.azs[count.index]}"
        "kubernetes.io/role/elb" = "1"
        Tier                     = "public"
      })
    }

    resource "aws_subnet" "private" {
      count             = var.az_count
      vpc_id            = aws_vpc.this.id
      cidr_block        = cidrsubnet(var.vpc_cidr, 4, count.index + var.az_count)
      availability_zone = local.azs[count.index]
      tags = merge(var.tags, {
        Name                              = "${local.name}-private-${local.azs[count.index]}"
        "kubernetes.io/role/internal-elb" = "1"
        Tier                              = "private"
      })
    }

    resource "aws_eip" "nat" {
      count  = var.enable_nat_gateway ? (var.single_nat_gateway ? 1 : var.az_count) : 0
      domain = "vpc"
      tags   = merge(var.tags, { Name = "${local.name}-nat-${count.index + 1}" })
      depends_on = [aws_internet_gateway.this]
    }

    resource "aws_nat_gateway" "this" {
      count         = var.enable_nat_gateway ? (var.single_nat_gateway ? 1 : var.az_count) : 0
      allocation_id = aws_eip.nat[count.index].id
      subnet_id     = aws_subnet.public[count.index].id
      tags          = merge(var.tags, { Name = "${local.name}-nat-${count.index + 1}" })
      depends_on    = [aws_internet_gateway.this]
    }

    resource "aws_route_table" "public" {
      vpc_id = aws_vpc.this.id
      route {
        cidr_block = "0.0.0.0/0"
        gateway_id = aws_internet_gateway.this.id
      }
      tags = merge(var.tags, { Name = "${local.name}-public" })
    }

    resource "aws_route_table" "private" {
      count  = var.enable_nat_gateway ? (var.single_nat_gateway ? 1 : var.az_count) : 1
      vpc_id = aws_vpc.this.id

      dynamic "route" {
        for_each = var.enable_nat_gateway ? [1] : []
        content {
          cidr_block     = "0.0.0.0/0"
          nat_gateway_id = aws_nat_gateway.this[var.single_nat_gateway ? 0 : count.index].id
        }
      }
      tags = merge(var.tags, { Name = "${local.name}-private-${count.index + 1}" })
    }

    resource "aws_route_table_association" "public" {
      count          = var.az_count
      subnet_id      = aws_subnet.public[count.index].id
      route_table_id = aws_route_table.public.id
    }

    resource "aws_route_table_association" "private" {
      count          = var.az_count
      subnet_id      = aws_subnet.private[count.index].id
      route_table_id = aws_route_table.private[var.single_nat_gateway ? 0 : min(count.index, length(aws_route_table.private) - 1)].id
    }

    resource "aws_flow_log" "this" {
      count                    = var.enable_flow_logs ? 1 : 0
      vpc_id                   = aws_vpc.this.id
      traffic_type             = "ALL"
      log_destination_type     = "cloud-watch-logs"
      log_destination          = aws_cloudwatch_log_group.flow_logs[0].arn
      iam_role_arn             = aws_iam_role.flow_logs[0].arn
      max_aggregation_interval = 60
      tags = merge(var.tags, { Name = "${local.name}-flow-logs" })
    }

    resource "aws_cloudwatch_log_group" "flow_logs" {
      count             = var.enable_flow_logs ? 1 : 0
      name              = "/aws/vpc/${local.name}/flow-logs"
      retention_in_days = var.flow_logs_retention_days
      tags              = var.tags
    }

    resource "aws_iam_role" "flow_logs" {
      count = var.enable_flow_logs ? 1 : 0
      name  = "${local.name}-flow-logs-role"
      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "vpc-flow-logs.amazonaws.com" } }]
      })
      tags = var.tags
    }

    resource "aws_iam_role_policy" "flow_logs" {
      count = var.enable_flow_logs ? 1 : 0
      name  = "${local.name}-flow-logs-policy"
      role  = aws_iam_role.flow_logs[0].id
      policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{ Action = ["logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents","logs:DescribeLogGroups","logs:DescribeLogStreams"], Effect = "Allow", Resource = "*" }]
      })
    }
""")

TERRAFORM_TEMPLATES["s3_bucket"] = textwrap.dedent("""\
    # S3 Bucket Module — Generated by Terragrunt Forge

    resource "aws_s3_bucket" "this" {
      bucket = "${var.bucket_name_prefix}-${var.environment}"
      tags   = merge(var.tags, { Name = "${var.bucket_name_prefix}-${var.environment}" })
    }

    resource "aws_s3_bucket_versioning" "this" {
      bucket = aws_s3_bucket.this.id
      versioning_configuration { status = var.versioning_enabled ? "Enabled" : "Suspended" }
    }

    resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
      bucket = aws_s3_bucket.this.id
      rule {
        apply_server_side_encryption_by_default {
          sse_algorithm     = var.kms_key_id != "" ? "aws:kms" : "AES256"
          kms_master_key_id = var.kms_key_id != "" ? var.kms_key_id : null
        }
        bucket_key_enabled = var.kms_key_id != "" ? true : false
      }
    }

    resource "aws_s3_bucket_public_access_block" "this" {
      bucket                  = aws_s3_bucket.this.id
      block_public_acls       = true
      block_public_policy     = true
      ignore_public_acls      = true
      restrict_public_buckets = true
    }
""")

TERRAFORM_TEMPLATES["eks"] = textwrap.dedent("""\
    # EKS Cluster Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_eks_cluster" "this" {
      name     = local.name
      version  = var.kubernetes_version
      role_arn = aws_iam_role.cluster.arn

      vpc_config {
        subnet_ids              = var.subnet_ids
        endpoint_private_access = var.endpoint_private_access
        endpoint_public_access  = var.endpoint_public_access
        security_group_ids      = [aws_security_group.cluster.id]
      }

      enabled_cluster_log_types = var.cluster_log_types

      encryption_config {
        provider { key_arn = var.kms_key_arn != "" ? var.kms_key_arn : aws_kms_key.eks[0].arn }
        resources = ["secrets"]
      }

      tags = merge(var.tags, { Name = local.name })
      depends_on = [
        aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy,
        aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceController,
      ]
    }

    resource "aws_kms_key" "eks" {
      count                   = var.kms_key_arn == "" ? 1 : 0
      description             = "KMS key for EKS ${local.name}"
      deletion_window_in_days = 7
      enable_key_rotation     = true
      tags                    = var.tags
    }

    resource "aws_iam_role" "cluster" {
      name = "${local.name}-cluster-role"
      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "eks.amazonaws.com" } }]
      })
      tags = var.tags
    }

    resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSClusterPolicy" {
      policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      role       = aws_iam_role.cluster.name
    }

    resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSVPCResourceController" {
      policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
      role       = aws_iam_role.cluster.name
    }

    resource "aws_security_group" "cluster" {
      name        = "${local.name}-cluster-sg"
      description = "EKS cluster control plane security group"
      vpc_id      = var.vpc_id
      egress { from_port = 0; to_port = 0; protocol = "-1"; cidr_blocks = ["0.0.0.0/0"] }
      tags = merge(var.tags, { Name = "${local.name}-cluster-sg" })
    }

    resource "aws_eks_node_group" "this" {
      for_each        = var.node_groups
      cluster_name    = aws_eks_cluster.this.name
      node_group_name = each.key
      node_role_arn   = aws_iam_role.node.arn
      subnet_ids      = var.subnet_ids
      instance_types  = each.value.instance_types
      capacity_type   = each.value.capacity_type
      disk_size       = each.value.disk_size

      scaling_config {
        desired_size = each.value.desired_size
        max_size     = each.value.max_size
        min_size     = each.value.min_size
      }

      update_config { max_unavailable_percentage = 25 }
      labels = merge(each.value.labels, { "node-group" = each.key })
      tags   = merge(var.tags, { Name = "${local.name}-${each.key}" })

      depends_on = [
        aws_iam_role_policy_attachment.node_AmazonEKSWorkerNodePolicy,
        aws_iam_role_policy_attachment.node_AmazonEKS_CNI_Policy,
        aws_iam_role_policy_attachment.node_AmazonEC2ContainerRegistryReadOnly,
      ]
    }

    resource "aws_iam_role" "node" {
      name = "${local.name}-node-role"
      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" } }]
      })
      tags = var.tags
    }

    resource "aws_iam_role_policy_attachment" "node_AmazonEKSWorkerNodePolicy" {
      policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
      role       = aws_iam_role.node.name
    }

    resource "aws_iam_role_policy_attachment" "node_AmazonEKS_CNI_Policy" {
      policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
      role       = aws_iam_role.node.name
    }

    resource "aws_iam_role_policy_attachment" "node_AmazonEC2ContainerRegistryReadOnly" {
      policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      role       = aws_iam_role.node.name
    }

    data "tls_certificate" "eks" { url = aws_eks_cluster.this.identity[0].oidc[0].issuer }

    resource "aws_iam_openid_connect_provider" "eks" {
      client_id_list  = ["sts.amazonaws.com"]
      thumbprint_list = [data.tls_certificate.eks.certificates[0].sha1_fingerprint]
      url             = aws_eks_cluster.this.identity[0].oidc[0].issuer
      tags            = var.tags
    }
""")

TERRAFORM_TEMPLATES["rds"] = textwrap.dedent("""\
    # RDS Instance Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_db_subnet_group" "this" {
      name       = "${local.name}-subnet-group"
      subnet_ids = var.subnet_ids
      tags       = merge(var.tags, { Name = "${local.name}-subnet-group" })
    }

    resource "aws_security_group" "this" {
      name        = "${local.name}-rds-sg"
      description = "Security group for RDS ${local.name}"
      vpc_id      = var.vpc_id
      dynamic "ingress" {
        for_each = length(var.allowed_cidr_blocks) > 0 || length(var.allowed_security_group_ids) > 0 ? [1] : []
        content {
          from_port       = var.port
          to_port         = var.port
          protocol        = "tcp"
          cidr_blocks     = var.allowed_cidr_blocks
          security_groups = var.allowed_security_group_ids
          description     = "Allow database access"
        }
      }
      egress { from_port = 0; to_port = 0; protocol = "-1"; cidr_blocks = ["0.0.0.0/0"]; description = "Allow all outbound" }
      tags = merge(var.tags, { Name = "${local.name}-rds-sg" })
    }

    resource "aws_kms_key" "rds" {
      count                   = var.kms_key_id == "" ? 1 : 0
      description             = "KMS key for RDS ${local.name}"
      deletion_window_in_days = 7
      enable_key_rotation     = true
      tags                    = var.tags
    }

    resource "aws_db_parameter_group" "this" {
      name   = "${local.name}-pg"
      family = var.parameter_group_family
      tags   = merge(var.tags, { Name = "${local.name}-pg" })
      lifecycle { create_before_destroy = true }
    }

    resource "aws_db_instance" "this" {
      identifier                  = local.name
      engine                      = var.engine
      engine_version              = var.engine_version
      instance_class              = var.instance_class
      parameter_group_name        = aws_db_parameter_group.this.name
      allocated_storage           = var.allocated_storage
      max_allocated_storage       = var.max_allocated_storage
      storage_type                = var.storage_type
      storage_encrypted           = true
      kms_key_id                  = var.kms_key_id != "" ? var.kms_key_id : aws_kms_key.rds[0].arn
      db_name                     = var.database_name
      username                    = var.master_username
      port                        = var.port
      manage_master_user_password = true
      db_subnet_group_name        = aws_db_subnet_group.this.name
      vpc_security_group_ids      = [aws_security_group.this.id]
      publicly_accessible         = false
      multi_az                    = var.multi_az
      backup_retention_period     = var.backup_retention_period
      backup_window               = var.backup_window
      maintenance_window          = var.maintenance_window
      copy_tags_to_snapshot       = true
      skip_final_snapshot         = var.skip_final_snapshot
      final_snapshot_identifier   = var.skip_final_snapshot ? null : "${local.name}-final"
      deletion_protection         = var.deletion_protection
      auto_minor_version_upgrade  = true
      tags                        = merge(var.tags, { Name = local.name })
    }
""")

TERRAFORM_TEMPLATES["dynamodb"] = textwrap.dedent("""\
    # DynamoDB Table Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_dynamodb_table" "this" {
      name         = local.name
      billing_mode = var.billing_mode
      hash_key     = var.hash_key
      range_key    = var.range_key != "" ? var.range_key : null

      attribute {
        name = var.hash_key
        type = var.hash_key_type
      }

      dynamic "attribute" {
        for_each = var.range_key != "" ? [1] : []
        content { name = var.range_key; type = var.range_key_type }
      }

      server_side_encryption { enabled = true }
      point_in_time_recovery { enabled = var.point_in_time_recovery_enabled }

      tags = merge(var.tags, { Name = local.name })
    }
""")

TERRAFORM_TEMPLATES["lambda"] = textwrap.dedent("""\
    # Lambda Function Module — Generated by Terragrunt Forge

    locals {
      name          = "${var.name}-${var.environment}"
      function_name = "${var.name}-${var.environment}-function"
    }

    resource "aws_iam_role" "lambda" {
      name = "${local.name}-lambda-role"
      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "lambda.amazonaws.com" } }]
      })
      tags = var.tags
    }

    resource "aws_iam_role_policy_attachment" "lambda_basic_execution" {
      policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      role       = aws_iam_role.lambda.name
    }

    resource "aws_cloudwatch_log_group" "lambda" {
      name              = "/aws/lambda/${local.function_name}"
      retention_in_days = var.log_retention_days
      tags              = var.tags
    }

    data "archive_file" "placeholder" {
      type        = "zip"
      output_path = "${path.module}/.placeholder/${local.function_name}.zip"
      source { content = "def handler(event, context): pass\\n"; filename = "index.py" }
    }

    resource "aws_lambda_function" "this" {
      function_name = local.function_name
      role          = aws_iam_role.lambda.arn
      handler       = var.handler
      runtime       = var.runtime
      timeout       = var.timeout
      memory_size   = var.memory_size
      filename      = data.archive_file.placeholder.output_path
      description   = var.description
      tags          = merge(var.tags, { Name = local.function_name })
    }
""")

TERRAFORM_TEMPLATES["iam_role"] = textwrap.dedent("""\
    # IAM Role Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_iam_role" "this" {
      name        = local.name
      description = var.description
      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{
          Effect    = "Allow"
          Principal = length(var.trusted_role_arns) > 0 ? { AWS = var.trusted_role_arns } : { Service = var.trusted_services }
          Action    = "sts:AssumeRole"
        }]
      })
      permissions_boundary = var.permissions_boundary_arn != "" ? var.permissions_boundary_arn : null
      tags = merge(var.tags, { Name = local.name })
    }

    resource "aws_iam_role_policy_attachment" "managed" {
      for_each   = toset(var.managed_policy_arns)
      role       = aws_iam_role.this.name
      policy_arn = each.value
    }

    resource "aws_iam_role_policy" "inline" {
      count = length(var.inline_policy_statements) > 0 ? 1 : 0
      name  = "${local.name}-inline-policy"
      role  = aws_iam_role.this.id
      policy = jsonencode({ Version = "2012-10-17", Statement = var.inline_policy_statements })
    }
""")

TERRAFORM_TEMPLATES["security_group"] = textwrap.dedent("""\
    # Security Group Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_security_group" "this" {
      name        = local.name
      description = var.description
      vpc_id      = var.vpc_id
      tags = merge(var.tags, { Name = local.name })
      lifecycle { create_before_destroy = true }
    }

    resource "aws_security_group_rule" "ingress" {
      for_each          = { for idx, rule in var.ingress_rules : tostring(idx) => rule }
      type              = "ingress"
      security_group_id = aws_security_group.this.id
      from_port         = each.value.from_port
      to_port           = each.value.to_port
      protocol          = each.value.protocol
      description       = each.value.description
      cidr_blocks       = lookup(each.value, "cidr_blocks", null)
    }

    resource "aws_security_group_rule" "egress" {
      for_each          = { for idx, rule in var.egress_rules : tostring(idx) => rule }
      type              = "egress"
      security_group_id = aws_security_group.this.id
      from_port         = each.value.from_port
      to_port           = each.value.to_port
      protocol          = each.value.protocol
      description       = each.value.description
      cidr_blocks       = lookup(each.value, "cidr_blocks", null)
    }
""")

TERRAFORM_TEMPLATES["secrets_manager"] = textwrap.dedent("""\
    # Secrets Manager Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_kms_key" "secrets" {
      count                   = var.kms_key_id == "" ? 1 : 0
      description             = "KMS key for ${local.name}"
      deletion_window_in_days = 7
      enable_key_rotation     = true
      tags                    = var.tags
    }

    resource "aws_secretsmanager_secret" "this" {
      name                    = "${local.name}/${var.secret_path}"
      description             = var.description
      kms_key_id              = var.kms_key_id != "" ? var.kms_key_id : aws_kms_key.secrets[0].arn
      recovery_window_in_days = var.recovery_window_in_days
      tags                    = merge(var.tags, { Name = local.name })
    }
""")

TERRAFORM_TEMPLATES["ecr"] = textwrap.dedent("""\
    # ECR Repository Module — Generated by Terragrunt Forge

    locals { name = "${var.name}-${var.environment}" }

    resource "aws_ecr_repository" "this" {
      name                 = local.name
      image_tag_mutability = var.image_tag_mutability
      force_delete         = var.force_delete
      image_scanning_configuration { scan_on_push = var.scan_on_push }
      encryption_configuration {
        encryption_type = var.kms_key_id != "" ? "KMS" : "AES256"
        kms_key         = var.kms_key_id != "" ? var.kms_key_id : null
      }
      tags = merge(var.tags, { Name = local.name })
    }

    resource "aws_ecr_lifecycle_policy" "this" {
      count      = var.enable_lifecycle_policy ? 1 : 0
      repository = aws_ecr_repository.this.name
      policy = jsonencode({
        rules = [{
          rulePriority = 1
          description  = "Remove untagged images after ${var.untagged_image_expiry_days} days"
          selection     = { tagStatus = "untagged", countType = "sinceImagePushed", countUnit = "days", countNumber = var.untagged_image_expiry_days }
          action        = { type = "expire" }
        }]
      })
    }
""")

# ---------- Variables templates ----------

VARIABLES_TEMPLATES: dict[str, str] = {}

VARIABLES_TEMPLATES["vpc"] = textwrap.dedent("""\
    variable "name"                    { type = string }
    variable "environment"             { type = string }
    variable "project"                 { type = string; default = "" }
    variable "vpc_cidr"                { type = string; default = "10.0.0.0/16" }
    variable "az_count"                { type = number; default = 3 }
    variable "enable_nat_gateway"      { type = bool;   default = true }
    variable "single_nat_gateway"      { type = bool;   default = false }
    variable "enable_flow_logs"        { type = bool;   default = true }
    variable "flow_logs_retention_days" { type = number; default = 30 }
    variable "tags"                    { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["s3_bucket"] = textwrap.dedent("""\
    variable "name"               { type = string }
    variable "environment"        { type = string }
    variable "project"            { type = string; default = "" }
    variable "bucket_name_prefix" { type = string }
    variable "versioning_enabled" { type = bool;   default = true }
    variable "kms_key_id"         { type = string; default = "" }
    variable "tags"               { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["eks"] = textwrap.dedent("""\
    variable "name"                    { type = string }
    variable "environment"             { type = string }
    variable "project"                 { type = string; default = "" }
    variable "vpc_id"                  { type = string }
    variable "subnet_ids"              { type = list(string) }
    variable "kubernetes_version"      { type = string; default = "1.29" }
    variable "endpoint_private_access" { type = bool;   default = true }
    variable "endpoint_public_access"  { type = bool;   default = true }
    variable "cluster_log_types"       { type = list(string); default = ["api","audit","authenticator","controllerManager","scheduler"] }
    variable "kms_key_arn"             { type = string; default = "" }
    variable "node_groups" {
      type = map(object({ instance_types = list(string), capacity_type = string, disk_size = number, desired_size = number, min_size = number, max_size = number, labels = map(string) }))
      default = { general = { instance_types = ["t3.medium"], capacity_type = "ON_DEMAND", disk_size = 50, desired_size = 2, min_size = 1, max_size = 5, labels = {} } }
    }
    variable "tags" { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["rds"] = textwrap.dedent("""\
    variable "name"                     { type = string }
    variable "environment"              { type = string }
    variable "project"                  { type = string; default = "" }
    variable "vpc_id"                   { type = string }
    variable "subnet_ids"               { type = list(string) }
    variable "engine"                   { type = string; default = "postgres" }
    variable "engine_version"           { type = string; default = "16.3" }
    variable "instance_class"           { type = string; default = "db.t3.medium" }
    variable "allocated_storage"        { type = number; default = 20 }
    variable "max_allocated_storage"    { type = number; default = 100 }
    variable "storage_type"             { type = string; default = "gp3" }
    variable "database_name"            { type = string; default = "appdb" }
    variable "master_username"          { type = string; default = "dbadmin" }
    variable "port"                     { type = number; default = 5432 }
    variable "multi_az"                 { type = bool;   default = true }
    variable "backup_retention_period"  { type = number; default = 7 }
    variable "backup_window"            { type = string; default = "03:00-04:00" }
    variable "maintenance_window"       { type = string; default = "sun:04:00-sun:05:00" }
    variable "skip_final_snapshot"      { type = bool;   default = false }
    variable "deletion_protection"      { type = bool;   default = true }
    variable "parameter_group_family"   { type = string; default = "postgres16" }
    variable "kms_key_id"               { type = string; default = "" }
    variable "allowed_cidr_blocks"      { type = list(string); default = [] }
    variable "allowed_security_group_ids" { type = list(string); default = [] }
    variable "tags"                     { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["dynamodb"] = textwrap.dedent("""\
    variable "name"                          { type = string }
    variable "environment"                   { type = string }
    variable "project"                       { type = string; default = "" }
    variable "billing_mode"                  { type = string; default = "PAY_PER_REQUEST" }
    variable "hash_key"                      { type = string }
    variable "hash_key_type"                 { type = string; default = "S" }
    variable "range_key"                     { type = string; default = "" }
    variable "range_key_type"                { type = string; default = "S" }
    variable "point_in_time_recovery_enabled" { type = bool; default = true }
    variable "tags"                          { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["lambda"] = textwrap.dedent("""\
    variable "name"              { type = string }
    variable "environment"       { type = string }
    variable "project"           { type = string; default = "" }
    variable "runtime"           { type = string; default = "python3.12" }
    variable "handler"           { type = string; default = "index.handler" }
    variable "timeout"           { type = number; default = 30 }
    variable "memory_size"       { type = number; default = 128 }
    variable "description"       { type = string; default = "" }
    variable "log_retention_days" { type = number; default = 14 }
    variable "tags"              { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["iam_role"] = textwrap.dedent("""\
    variable "name"                      { type = string }
    variable "environment"               { type = string }
    variable "project"                   { type = string; default = "" }
    variable "description"               { type = string; default = "" }
    variable "trusted_services"          { type = list(string); default = [] }
    variable "trusted_role_arns"         { type = list(string); default = [] }
    variable "managed_policy_arns"       { type = list(string); default = [] }
    variable "inline_policy_statements"  { type = list(any); default = [] }
    variable "permissions_boundary_arn"  { type = string; default = "" }
    variable "tags"                      { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["security_group"] = textwrap.dedent("""\
    variable "name"          { type = string }
    variable "environment"   { type = string }
    variable "project"       { type = string; default = "" }
    variable "vpc_id"        { type = string }
    variable "description"   { type = string; default = "Managed by Terraform" }
    variable "ingress_rules" { type = list(any); default = [] }
    variable "egress_rules" {
      type    = list(any)
      default = [{ from_port = 0, to_port = 0, protocol = "-1", description = "Allow all outbound", cidr_blocks = ["0.0.0.0/0"] }]
    }
    variable "tags" { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["secrets_manager"] = textwrap.dedent("""\
    variable "name"                     { type = string }
    variable "environment"              { type = string }
    variable "project"                  { type = string; default = "" }
    variable "secret_path"              { type = string }
    variable "description"              { type = string; default = "" }
    variable "kms_key_id"               { type = string; default = "" }
    variable "recovery_window_in_days"  { type = number; default = 30 }
    variable "tags"                     { type = map(string); default = {} }
""")

VARIABLES_TEMPLATES["ecr"] = textwrap.dedent("""\
    variable "name"                        { type = string }
    variable "environment"                 { type = string }
    variable "project"                     { type = string; default = "" }
    variable "image_tag_mutability"        { type = string; default = "IMMUTABLE" }
    variable "scan_on_push"                { type = bool;   default = true }
    variable "force_delete"                { type = bool;   default = false }
    variable "kms_key_id"                  { type = string; default = "" }
    variable "enable_lifecycle_policy"     { type = bool;   default = true }
    variable "untagged_image_expiry_days"  { type = number; default = 14 }
    variable "tags"                        { type = map(string); default = {} }
""")

# ---------- Outputs templates ----------

OUTPUTS_TEMPLATES: dict[str, str] = {
    "vpc": textwrap.dedent("""\
        output "vpc_id"              { value = aws_vpc.this.id }
        output "vpc_cidr_block"      { value = aws_vpc.this.cidr_block }
        output "public_subnet_ids"   { value = aws_subnet.public[*].id }
        output "private_subnet_ids"  { value = aws_subnet.private[*].id }
        output "nat_gateway_ids"     { value = aws_nat_gateway.this[*].id }
        output "internet_gateway_id" { value = aws_internet_gateway.this.id }
        output "availability_zones"  { value = local.azs }
    """),
    "s3_bucket": textwrap.dedent("""\
        output "bucket_id"   { value = aws_s3_bucket.this.id }
        output "bucket_arn"  { value = aws_s3_bucket.this.arn }
    """),
    "eks": textwrap.dedent("""\
        output "cluster_name"     { value = aws_eks_cluster.this.name }
        output "cluster_endpoint" { value = aws_eks_cluster.this.endpoint }
        output "cluster_arn"      { value = aws_eks_cluster.this.arn }
        output "cluster_ca_data"  { value = aws_eks_cluster.this.certificate_authority[0].data }
        output "oidc_provider_arn" { value = aws_iam_openid_connect_provider.eks.arn }
        output "cluster_security_group_id" { value = aws_security_group.cluster.id }
    """),
    "rds": textwrap.dedent("""\
        output "db_instance_endpoint" { value = aws_db_instance.this.endpoint }
        output "db_instance_arn"      { value = aws_db_instance.this.arn }
        output "db_instance_id"       { value = aws_db_instance.this.id }
        output "db_security_group_id" { value = aws_security_group.this.id }
    """),
    "dynamodb": textwrap.dedent("""\
        output "table_name" { value = aws_dynamodb_table.this.name }
        output "table_arn"  { value = aws_dynamodb_table.this.arn }
        output "table_id"   { value = aws_dynamodb_table.this.id }
    """),
    "lambda": textwrap.dedent("""\
        output "function_name" { value = aws_lambda_function.this.function_name }
        output "function_arn"  { value = aws_lambda_function.this.arn }
        output "invoke_arn"    { value = aws_lambda_function.this.invoke_arn }
        output "role_arn"      { value = aws_iam_role.lambda.arn }
    """),
    "iam_role": textwrap.dedent("""\
        output "role_arn"  { value = aws_iam_role.this.arn }
        output "role_name" { value = aws_iam_role.this.name }
        output "role_id"   { value = aws_iam_role.this.unique_id }
    """),
    "security_group": textwrap.dedent("""\
        output "security_group_id"  { value = aws_security_group.this.id }
        output "security_group_arn" { value = aws_security_group.this.arn }
    """),
    "secrets_manager": textwrap.dedent("""\
        output "secret_arn"  { value = aws_secretsmanager_secret.this.arn }
        output "secret_name" { value = aws_secretsmanager_secret.this.name }
        output "secret_id"   { value = aws_secretsmanager_secret.this.id }
    """),
    "ecr": textwrap.dedent("""\
        output "repository_url"  { value = aws_ecr_repository.this.repository_url }
        output "repository_arn"  { value = aws_ecr_repository.this.arn }
        output "repository_name" { value = aws_ecr_repository.this.name }
    """),
}

# ─── Resource category mapping ──────────────────────────────────────────────────

RESOURCE_CATEGORY: dict[str, str] = {
    "vpc": "network",
    "security_group": "network",
    "eks": "compute",
    "lambda": "compute",
    "rds": "data",
    "dynamodb": "data",
    "s3_bucket": "storage",
    "ecr": "containers",
    "iam_role": "security",
    "secrets_manager": "security",
}


# ═══════════════════════════════════════════════════════════════════════════════
#  Generators
# ═══════════════════════════════════════════════════════════════════════════════

def _generate_root_terragrunt(project: ProjectConfig) -> str:
    """Generate the root terragrunt.hcl content."""
    return textwrap.dedent(f"""\
        # Root Terragrunt Configuration
        # Generated by Terragrunt Forge

        locals {{
          account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl", "empty.hcl"), {{ locals = {{}} }})
          region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl", "empty.hcl"), {{ locals = {{}} }})
          env_vars     = read_terragrunt_config(find_in_parent_folders("env.hcl", "empty.hcl"), {{ locals = {{}} }})

          account_id   = try(local.account_vars.locals.account_id, "")
          region       = try(local.region_vars.locals.aws_region, "{project.default_region}")
          environment  = try(local.env_vars.locals.environment, "dev")
          organization = "{project.organization}"
          project      = "{project.name}"
        }}

        remote_state {{
          backend = "s3"
          config = {{
            bucket         = "${{local.organization}}-terraform-state-${{local.account_id}}"
            key            = "${{path_relative_to_include()}}/terraform.tfstate"
            region         = local.region
            encrypt        = true
            dynamodb_table = "${{local.organization}}-terraform-locks"
          }}
          generate = {{
            path      = "backend.tf"
            if_exists = "overwrite_terragrunt"
          }}
        }}

        generate "provider" {{
          path      = "provider.tf"
          if_exists = "overwrite_terragrunt"
          contents  = <<EOF
        terraform {{
          required_version = ">= 1.0"
          required_providers {{
            aws = {{
              source  = "hashicorp/aws"
              version = "~> 5.0"
            }}
          }}
        }}

        provider "aws" {{
          region = "${{local.region}}"
          default_tags {{
            tags = {{
              Environment  = "${{local.environment}}"
              Project      = "${{local.project}}"
              Organization = "${{local.organization}}"
              ManagedBy    = "terragrunt"
            }}
          }}
        }}
        EOF
        }}

        inputs = {{
          environment  = local.environment
          project      = local.project
          region       = local.region
          organization = local.organization
        }}
    """)


def _generate_env_hcl(env: str) -> str:
    return f'locals {{\n  environment = "{env}"\n}}\n'


def _generate_region_hcl(region: str) -> str:
    return f'locals {{\n  aws_region = "{region}"\n}}\n'


def _generate_child_terragrunt(
    resource: ResourceConfig,
    project: ProjectConfig,
    env: str,
) -> str:
    """Generate a child terragrunt.hcl for a specific resource."""
    resource_type = resource.type.value
    category = RESOURCE_CATEGORY.get(resource_type, "general")

    lines = [
        "# Terragrunt Configuration",
        f"# Resource: {resource.name} ({resource_type})",
        "# Generated by Terragrunt Forge",
        "",
        'include "root" {',
        "  path = find_in_parent_folders()",
        "}",
        "",
        "terraform {",
        f'  source = "${{dirname(find_in_parent_folders())}}//modules/{resource_type}"',
        "}",
        "",
    ]

    # Add dependency blocks
    for dep in resource.depends_on:
        dep_type = dep  # could be a resource type or name
        dep_category = RESOURCE_CATEGORY.get(dep_type, "general")
        lines.extend([
            f'dependency "{dep}" {{',
            f'  config_path = "../../{dep_category}/{dep}"',
            "",
            "  mock_outputs = {",
        ])
        # Add common mock outputs based on dependency type
        if dep in ("vpc",):
            lines.extend([
                '    vpc_id             = "vpc-mock12345"',
                '    private_subnet_ids = ["subnet-mock1", "subnet-mock2", "subnet-mock3"]',
                '    public_subnet_ids  = ["subnet-mock4", "subnet-mock5", "subnet-mock6"]',
            ])
        elif dep in ("security_group",):
            lines.append('    security_group_id = "sg-mock12345"')
        else:
            lines.append(f'    {dep}_id = "mock-{dep}-id"')

        lines.extend([
            "  }",
            '  mock_outputs_allowed_terraform_commands = ["validate", "plan"]',
            "}",
            "",
        ])

    # Inputs
    lines.append("inputs = {")
    lines.append(f'  name = "{resource.name}"')

    # Add dependency references in inputs
    for dep in resource.depends_on:
        if dep == "vpc":
            lines.append(f"  vpc_id     = dependency.{dep}.outputs.vpc_id")
            lines.append(f"  subnet_ids = dependency.{dep}.outputs.private_subnet_ids")

    # Add resource-specific variables
    for key, value in resource.variables.items():
        if isinstance(value, str):
            lines.append(f'  {key} = "{value}"')
        elif isinstance(value, bool):
            lines.append(f"  {key} = {str(value).lower()}")
        elif isinstance(value, (int, float)):
            lines.append(f"  {key} = {value}")
        elif isinstance(value, list):
            items = ", ".join(f'"{v}"' if isinstance(v, str) else str(v) for v in value)
            lines.append(f"  {key} = [{items}]")
        else:
            lines.append(f"  {key} = {json.dumps(value)}")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def _write_project(project: ProjectConfig) -> dict[str, str]:
    """Generate all files for a project. Returns dict of relative path → content."""
    files: dict[str, str] = {}
    base = project.output_dir

    # Root terragrunt.hcl
    files[f"{base}/terragrunt.hcl"] = _generate_root_terragrunt(project)

    # Empty.hcl fallback
    files[f"{base}/empty.hcl"] = ""

    # Collect all unique resource types to generate modules
    resource_types_used: set[str] = set()

    for stack in project.stacks:
        env = stack.environment.value
        region = stack.region

        # env.hcl
        files[f"{base}/live/{env}/env.hcl"] = _generate_env_hcl(env)

        # region.hcl
        files[f"{base}/live/{env}/{region}/region.hcl"] = _generate_region_hcl(region)

        for resource in stack.resources:
            rt = resource.type.value
            resource_types_used.add(rt)
            category = RESOURCE_CATEGORY.get(rt, "general")

            # Child terragrunt.hcl
            child_path = f"{base}/live/{env}/{region}/{category}/{resource.name}/terragrunt.hcl"
            files[child_path] = _generate_child_terragrunt(resource, project, env)

    # Generate Terraform modules for each resource type used
    for rt in resource_types_used:
        if rt in TERRAFORM_TEMPLATES:
            files[f"{base}/modules/{rt}/main.tf"] = TERRAFORM_TEMPLATES[rt]
        if rt in VARIABLES_TEMPLATES:
            files[f"{base}/modules/{rt}/variables.tf"] = VARIABLES_TEMPLATES[rt]
        if rt in OUTPUTS_TEMPLATES:
            files[f"{base}/modules/{rt}/outputs.tf"] = OUTPUTS_TEMPLATES[rt]

    return files


# ═══════════════════════════════════════════════════════════════════════════════
#  MCP Tools
# ═══════════════════════════════════════════════════════════════════════════════

@mcp.tool()
def list_resource_types() -> str:
    """List all supported AWS resource types that can be generated."""
    rows = []
    for rt in ResourceType:
        cat = RESOURCE_CATEGORY.get(rt.value, "general")
        rows.append(f"- **{rt.value}** (category: {cat})")
    return "Supported resource types:\n" + "\n".join(rows)


@mcp.tool()
def generate_terragrunt_project(
    name: str,
    organization: str,
    stacks_json: str,
    output_dir: str = "infrastructure",
    default_region: str = "us-west-2",
    environments: str = "dev,staging,prod",
    write_to_disk: bool = False,
    disk_base_path: str = ".",
) -> str:
    """
    Generate a complete Terragrunt project with all stacks and modules.

    Args:
        name: Project name (e.g. 'data-platform')
        organization: Organization name (e.g. 'acmecorp')
        stacks_json: JSON array of stack definitions. Each stack:
            {
              "name": "network",
              "environment": "dev",
              "region": "us-west-2",
              "resources": [
                {
                  "name": "main-vpc",
                  "type": "vpc",
                  "variables": {"vpc_cidr": "10.0.0.0/16", "az_count": 3},
                  "depends_on": []
                }
              ]
            }
        output_dir: Output directory name within the project (default: 'infrastructure')
        default_region: Default AWS region (default: 'us-west-2')
        environments: Comma-separated environments (default: 'dev,staging,prod')
        write_to_disk: If True, write files to disk at disk_base_path
        disk_base_path: Base directory to write files to (default: current dir)

    Returns:
        Summary of generated files with their contents (or paths if written to disk).
    """
    # Parse stacks
    try:
        stacks_raw = json.loads(stacks_json)
    except json.JSONDecodeError as e:
        return f"ERROR: Invalid stacks_json: {e}"

    envs = [Environment(e.strip()) for e in environments.split(",")]

    stacks = []
    for s in stacks_raw:
        resources = []
        for r in s.get("resources", []):
            resources.append(ResourceConfig(
                name=r["name"],
                type=ResourceType(r["type"]),
                variables=r.get("variables", {}),
                depends_on=r.get("depends_on", []),
            ))
        stacks.append(StackConfig(
            name=s["name"],
            environment=Environment(s.get("environment", "dev")),
            region=s.get("region", default_region),
            resources=resources,
        ))

    project = ProjectConfig(
        name=name,
        organization=organization,
        environments=envs,
        default_region=default_region,
        stacks=stacks,
        output_dir=output_dir,
    )

    files = _write_project(project)

    if write_to_disk:
        base = Path(disk_base_path)
        written = []
        for rel_path, content in files.items():
            full_path = base / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            written.append(str(full_path))
        return f"✅ Generated {len(written)} files under {base}:\n" + "\n".join(f"  - {p}" for p in sorted(written))
    else:
        # Return file contents for Claude to present
        parts = [f"Generated {len(files)} files:\n"]
        for rel_path, content in sorted(files.items()):
            parts.append(f"### `{rel_path}`\n```hcl\n{content}\n```\n")
        return "\n".join(parts)


@mcp.tool()
def generate_terraform_module(
    resource_type: str,
    name: str = "example",
) -> str:
    """
    Generate a single Terraform module (main.tf, variables.tf, outputs.tf) for a resource type.

    Args:
        resource_type: One of: vpc, s3_bucket, eks, rds, dynamodb, lambda, iam_role, security_group, secrets_manager, ecr
        name: Resource name to use in the template

    Returns:
        The complete Terraform module files.
    """
    rt = resource_type.lower()
    if rt not in TERRAFORM_TEMPLATES:
        return f"ERROR: Unknown resource type '{rt}'. Use list_resource_types to see options."

    parts = [f"## Terraform Module: {rt}\n"]
    parts.append(f"### `modules/{rt}/main.tf`\n```hcl\n{TERRAFORM_TEMPLATES[rt]}\n```\n")
    if rt in VARIABLES_TEMPLATES:
        parts.append(f"### `modules/{rt}/variables.tf`\n```hcl\n{VARIABLES_TEMPLATES[rt]}\n```\n")
    if rt in OUTPUTS_TEMPLATES:
        parts.append(f"### `modules/{rt}/outputs.tf`\n```hcl\n{OUTPUTS_TEMPLATES[rt]}\n```\n")
    return "\n".join(parts)


@mcp.tool()
def generate_child_terragrunt_hcl(
    resource_name: str,
    resource_type: str,
    project_name: str = "my-project",
    organization: str = "myorg",
    environment: str = "dev",
    region: str = "us-west-2",
    variables_json: str = "{}",
    depends_on: str = "",
) -> str:
    """
    Generate a single child terragrunt.hcl file for a resource.

    Args:
        resource_name: Name of the resource (e.g. 'main-vpc')
        resource_type: Resource type (e.g. 'vpc', 'eks', 'rds')
        project_name: Project name
        organization: Organization name
        environment: Environment (dev, staging, prod)
        region: AWS region
        variables_json: JSON object of input variables
        depends_on: Comma-separated list of dependency resource types (e.g. 'vpc,security_group')

    Returns:
        The terragrunt.hcl file content.
    """
    try:
        variables = json.loads(variables_json)
    except json.JSONDecodeError as e:
        return f"ERROR: Invalid variables_json: {e}"

    deps = [d.strip() for d in depends_on.split(",") if d.strip()]

    resource = ResourceConfig(
        name=resource_name,
        type=ResourceType(resource_type),
        variables=variables,
        depends_on=deps,
    )

    project = ProjectConfig(
        name=project_name,
        organization=organization,
        default_region=region,
    )

    content = _generate_child_terragrunt(resource, project, environment)
    return f"### `live/{environment}/{region}/{RESOURCE_CATEGORY.get(resource_type, 'general')}/{resource_name}/terragrunt.hcl`\n```hcl\n{content}\n```"


@mcp.tool()
def get_environment_defaults(environment: str) -> str:
    """
    Get recommended variable defaults for a given environment.

    Args:
        environment: One of 'dev', 'staging', 'prod'

    Returns:
        Recommended defaults for the environment.
    """
    defaults = {
        "dev": {
            "vpc": {"single_nat_gateway": True, "enable_flow_logs": True, "flow_logs_retention_days": 14},
            "eks": {"node_groups": {"general": {"instance_types": ["t3.medium"], "desired_size": 2, "min_size": 1, "max_size": 5}}},
            "rds": {"instance_class": "db.t3.medium", "multi_az": False, "deletion_protection": False, "skip_final_snapshot": True, "backup_retention_period": 3},
            "s3_bucket": {"versioning_enabled": True},
        },
        "staging": {
            "vpc": {"single_nat_gateway": True, "enable_flow_logs": True, "flow_logs_retention_days": 30},
            "eks": {"node_groups": {"general": {"instance_types": ["t3.large"], "desired_size": 3, "min_size": 2, "max_size": 8}}},
            "rds": {"instance_class": "db.t3.large", "multi_az": True, "deletion_protection": True, "skip_final_snapshot": False, "backup_retention_period": 7},
            "s3_bucket": {"versioning_enabled": True},
        },
        "prod": {
            "vpc": {"single_nat_gateway": False, "enable_flow_logs": True, "flow_logs_retention_days": 90},
            "eks": {"node_groups": {"general": {"instance_types": ["m5.xlarge"], "desired_size": 5, "min_size": 3, "max_size": 20}}},
            "rds": {"instance_class": "db.r6g.large", "multi_az": True, "deletion_protection": True, "skip_final_snapshot": False, "backup_retention_period": 30},
            "s3_bucket": {"versioning_enabled": True},
        },
    }

    env = environment.lower()
    if env not in defaults:
        return f"ERROR: Unknown environment '{env}'. Use dev, staging, or prod."

    return json.dumps(defaults[env], indent=2)


# ═══════════════════════════════════════════════════════════════════════════════
#  Resources (context for Claude)
# ═══════════════════════════════════════════════════════════════════════════════

@mcp.resource("terragrunt://skill")
def get_skill() -> str:
    """Full Terragrunt Forge skill reference — resource types, variables, outputs, and dependency patterns."""
    if SKILL_PATH.exists():
        return SKILL_PATH.read_text()
    return "Skill file not found at: " + str(SKILL_PATH)


@mcp.resource("terragrunt://conventions")
def get_conventions() -> str:
    """Terragrunt directory conventions and best practices."""
    return textwrap.dedent("""\
        # Terragrunt Conventions

        ## Directory Layout
        ```
        infrastructure/
        ├── terragrunt.hcl          # Root: remote state, provider gen
        ├── modules/                # Terraform modules
        │   ├── vpc/
        │   ├── eks/
        │   └── ...
        └── live/                   # Per-environment configs
            ├── dev/
            │   ├── env.hcl
            │   └── us-west-2/
            │       ├── region.hcl
            │       ├── network/vpc/terragrunt.hcl
            │       └── compute/eks/terragrunt.hcl
            ├── staging/
            └── prod/
        ```

        ## Dependency Chain
        VPC → Security Groups → EKS / RDS
        VPC → S3 (flow logs)
        EKS → IAM Roles (IRSA)
        RDS → Secrets Manager (credentials)

        ## Security Defaults
        - KMS encryption for all data stores
        - S3 public access always blocked
        - Private subnets for databases/compute
        - VPC Flow Logs enabled
        - All resources tagged
    """)


# ═══════════════════════════════════════════════════════════════════════════════
#  Entrypoint
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    mcp.run()
