"""
Stack Forge - Self-Service Infrastructure Templating Engine

A CLI tool for generating production-ready Terraform and Terragrunt
configurations from reusable templates.
"""

try:
    # _version.py is auto-generated by hatch-vcs at build / editable-install time
    from stack_forge._version import __version__
except ImportError:
    try:
        # Fallback: installed wheel has this in package metadata
        from importlib.metadata import PackageNotFoundError, version

        __version__ = version("stack-forge-infra")
    except (ImportError, PackageNotFoundError):
        __version__ = "0.0.0.dev0"

__author__ = "Praneeth Turlapati"
